version: "3"

services:
  api:
    build: 
        context: ./node                         #que me construya utilizando dentro del contexto actual la carpeta node (hace build segun el Dockerfile que encuentre)
    depends_on:                                 #para decir que este docker depende de db, pero no asegura que se ejecute correctamente antes
      - db
    ports:
      - "9001-9002:3000"                        #asigna un rango de puertos del servidor a los dockers (para escalar)
    volumes:
        - ./node:/usr/src                       #monta mi contexto de build en la carpeta src
        - /usr/src/node_modules                 #como hay archivos que no deben modificarse, le especificas el nombre para que no los toque
    container_name: 
        tnp-node-api
    deploy:
        replicas: 2                             #levanta 2 instancias. hay que ejecutar el docker-compose up --compatibility
  db:
    build: 
        context: ./mysql
    environment:                    
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "9003:3306"
      - "9004:8080"
    container_name: 
        tnp-node-db 
  lb:
    build: 
        context: ./nginx                        #levanta el balanceador de carga
    ports:
      - "9000:80"
    container_name: 
        tnp-node-lb