version: "3"

services:
                          #levanta 2 instancias. hay que ejecutar el docker-compose up --compatibility
  db:
    build: 
        context: ./mysql
    environment:                    
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_USER: ${MYSQL_USER} 
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
            - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
            - db_data:/var/lib/mysql
    ports:
      - "9003:3306"
      - "9004:8080"
    networks: 
      tnp_net:
        aliases: 
          - db


volumes:
    db_data:

networks:
  tnp_net: